[package]
name = "dioxus-slides"
version = "0.0.1"
authors = ["Alexander Jophus Trelore"]
edition = "2021"
description = "A slides component library for dioxus"
repository = "https://github.com/alexanderjophus/dioxus-slides"
license = "MIT OR Apache-2.0"
keywords = ["ui", "gui", "react", "wasm", "dioxus"]
categories = ["wasm", "gui", "web-programming"]

[dependencies]
dioxus = "0.4.0"
dioxus-slides-macro = "0.0.1"
