[package]
name = "dioxus-slides-macro"
version.workspace = true
authors = ["Alexander Jophus Trelore"]
edition = "2021"
description = "A slidable macro library for dioxus-slides"
repository = "https://github.com/alexanderjophus/dioxus-slides"
license = "MIT OR Apache-2.0"
keywords = ["ui", "gui", "react", "wasm", "dioxus"]
categories = ["wasm", "gui", "web-programming"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
