name: Publish to crates.io on tag

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces
      - name: Login to crates.io
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: login
          args: ${{ secrets.CRATES_TOKEN }}
      - name: Publish to crates.io
        run: |
          cargo workspaces version -y ${{ GITHUB_REF_NAME }}
